#!/bin/bash
#ToDo:
# Need to add recursive dir serching. 

BOOTDIR=/var/tftp/boot  
FSMOUNTDIR=/var/nfs/rootfs

IMAGEDIR=/home/sjs205/svn/swannprojects/buildrootfs_s3c6410/trunk/source/buildroot-2011.08/output/images
KERNEL=/uImage
FS=/rootfs.ext2

echo; echo; echo "NFS setup script"; echo; echo

echo; echo "Copying kernel: ${KERNELARRAY[${OPTION}]}"
echo "to ${BOOTDIR}"
cp ${IMAGEDIR}${KERNEL} ${BOOTDIR}/uImage

echo; echo

echo "Checking for previously mounted filesystems."; echo;

mount | grep ${FSMOUNTDIR}
   if [ $? == 0 ]; then
    echo "Shutting down nfs-kernel-server daemon..."
    /etc/init.d/nfs-kernel-server stop

    echo "unmounting previous filesystem..."
    umount ${FSMOUNTDIR} -f

    echo "Starting nfs-kernel-server"
    /etc/init.d/nfs-kernel-server start
fi



echo; echo "Mounting filsystem: ${IMAGEDIR}${FS}"
echo "at  ${FSMOUNTDIR}"
mount -t ext2 -o loop ${IMAGEDIR}${FS} ${FSMOUNTDIR}

echo; echo "NFS setup complete..."; echo
